"""
Django settings for grocery_shop project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import django_heroku
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6nun)vjhkct2!x&1)%@moomipk59v)dj0xi360o6ia5h-_+9$u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'GroceryApp',
    'userauths',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GroceryShopProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        # 'DIRS': ['GroceryApp/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GroceryShopProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    # 'default':{
    # 'ENGINE':'mssql',                   
    # 'NAME':'database(24_11AM)',                    
    # 'HOST':'TOQTOQ\SQLEXPRESS', 
    # 'PORT':'',                           
    # 'OPTIONS': {
    #     'driver': 'ODBC Driver 17 for SQL Server',
    #     }
    # }
    # 'default':{
    #     'ENGINE':'mssql',                   
    #     'NAME':'GroceryShop(21_3PM)',                    
    #     'HOST':'Mariamu', 
    #     'PORT':'',                           
    #     'OPTIONS': {
    #     'driver': 'ODBC Driver 17 for SQL Server',
    #     }
    #  }
    # 'default':{
    # 'ENGINE':'django.db.backends.postgresql',                   
    # 'NAME':'railway',                    
    # 'USER' :'postgres',
    # 'PASSWORD' : 'cc-BC4AbB---61gB65F*BgCcdFbefefF', 
    # 'HOST':'viaduct.proxy.rlwy.net', 
    # 'PORT':'32970'   
    # }    
    'default':{
    'ENGINE':'django.db.backends.postgresql',                   
    'NAME':'groceryapp',                    
    'USER' :'root',
    'PASSWORD' : 'YUZYebXG82AEY1hu6jLx3KRrLLBcdJ87', 
    'HOST':'dpg-cm4gu6mn7f5s73bvcgpg-a.oregon-postgres.render.com', 
    'PORT':'5432'   
    }                
   
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
django_heroku.settings(locals())


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS ={
    'site_header' : 'Grocery Shop',
    'site_brand' : 'You order, We deliver',
    'site_logo' : 'img/logo.png',
    'copyright' : 'grocery.shop.com',
}

AUTH_USER_MODEL = 'userauths.User'
APPEND_SLASH = False

