# Generated by Django 4.2.8 on 2023-12-18 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GroceryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(db_collation='Arabic_CI_AI', max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Address',
                'db_table': 'groceryapp_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default='0.99', max_digits=14, null=True)),
                ('paid_status', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('product_status', models.CharField(choices=[('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], db_collation='Arabic_CI_AI', default='Processing', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cart Order',
                'db_table': 'groceryapp_cartorder',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GroceryApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wishlist',
                'db_table': 'groceryapp_wishlist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CartOrderItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_status', models.CharField(blank=True, db_collation='Arabic_CI_AI', max_length=200, null=True)),
                ('item', models.CharField(blank=True, db_collation='Arabic_CI_AI', max_length=200, null=True)),
                ('image', models.CharField(blank=True, db_collation='Arabic_CI_AI', max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default='0.99', max_digits=14, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default='0.99', max_digits=25, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroceryApp.cartorder')),
            ],
            options={
                'verbose_name_plural': 'Cart Order Items',
                'db_table': 'groceryapp_cartorderitems',
                'managed': True,
            },
        ),
    ]
