# Generated by Django 4.2.8 on 2023-12-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0002_address_cartorder_wishlist_cartorderitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'managed': True, 'verbose_name_plural': 'Address'},
        ),
    ]
