# Generated by Django 4.2.8 on 2023-12-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GroceryApp", "0002_cartorder_product_brand_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingdetails",
            name="payment_method",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
