# Generated by Django 4.2.8 on 2023-12-25 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("GroceryApp", "0003_alter_billingdetails_payment_method"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="GroceryApp_category",
        ),
    ]
