# Generated by Django 4.2.8 on 2023-12-25 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("GroceryApp", "0004_alter_category_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="groceryapp_category",
        ),
    ]
