# Generated by Django 4.2.8 on 2023-12-25 07:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("GroceryApp", "0005_alter_category_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="billingdetails",
            table="groceryapp_billingdetails",
        ),
        migrations.AlterModelTable(
            name="cartorder",
            table="groceryapp_cartorder",
        ),
        migrations.AlterModelTable(
            name="cartorderitems",
            table="groceryapp_cartorderitems",
        ),
        migrations.AlterModelTable(
            name="product",
            table="groceryapp_product",
        ),
        migrations.AlterModelTable(
            name="productimages",
            table="groceryapp_productimages",
        ),
        migrations.AlterModelTable(
            name="productreviews",
            table="groceryapp_productreviews",
        ),
        migrations.AlterModelTable(
            name="wishlist",
            table="groceryapp_wishlist",
        ),
    ]
