# Generated by Django 4.2.8 on 2023-12-20 18:28

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ("GroceryApp", "0005_rename_product_reviews_productreviews"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartorderitems",
            name="item",
        ),
        migrations.AddField(
            model_name="cartorderitems",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="GroceryApp.product",
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="cart_order_item_images/"
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="invoice_number",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh12345",
                length=10,
                max_length=20,
                prefix="sku",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=25, null=True
            ),
        ),
    ]
