# Generated by Django 4.2.8 on 2023-12-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0006_alter_billingdetails_table_alter_cartorder_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_description',
            new_name='product_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(default='Ogani', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_nationality',
            field=models.CharField(default='Egypt', max_length=100),
        ),
    ]
