# Generated by Django 4.2.8 on 2023-12-26 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GroceryApp', '0006_alter_billingdetails_table_alter_cartorder_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_description',
            new_name='product_description',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
