# Generated by Django 4.2.8 on 2023-12-20 18:29

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "GroceryApp",
            "0006_remove_cartorderitems_item_cartorderitems_product_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorderitems",
            name="invoice_number",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh12345",
                length=10,
                max_length=20,
                prefix="",
                unique=True,
            ),
        ),
    ]
