# Generated by Django 4.2.8 on 2023-12-26 08:34

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0007_rename_p_description_product_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(default='Fresh Food', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_nationality',
            field=models.CharField(default='Egypt', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='pro', unique=True),
        ),
    ]
