# Generated by Django 4.2.8 on 2023-12-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0008_remove_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='added_by',
        ),
    ]
