# Generated by Django 4.2.8 on 2023-12-21 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("GroceryApp", "0008_rename_product_status_cartorder_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartorder",
            old_name="id",
            new_name="ct_ord_id",
        ),
        migrations.RenameField(
            model_name="cartorderitems",
            old_name="id",
            new_name="ct_ord_it_id",
        ),
    ]
