# Generated by Django 4.2.8 on 2023-12-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0009_rename_user_product_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('PIECE', 'piece'), ('PACK', 'Pack'), ('KG', 'Kilogram'), ('SLICE', 'Slice'), ('BOTTLE', 'Bottle'), ('CAN', 'Can')], default='PIECE', max_length=6),
        ),
    ]
