# Generated by Django 4.2.8 on 2023-12-22 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0010_alter_cartorderitems_invoice_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='status',
            new_name='delivered_status',
        ),
        migrations.AddField(
            model_name='address',
            name='apartment',
            field=models.CharField(db_collation='Arabic_CI_AI', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(db_collation='Arabic_CI_AI', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(db_collation='Arabic_CI_AI', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='governorate',
            field=models.CharField(db_collation='Arabic_CI_AI', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GroceryApp.cartorder'),
        ),
        migrations.AddField(
            model_name='address',
            name='payment_method',
            field=models.CharField(db_collation='Arabic_CI_AI', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='payment_status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(db_collation='Arabic_CI_AI', max_length=20, null=True),
        ),
    ]
