# Generated by Django 4.2.8 on 2023-12-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0012_alter_product_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, default='Freshly sourced from our brand selection.', max_length=400, null=True),
        ),
    ]
