# Generated by Django 4.2.8 on 2023-12-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0012_rename_address_billingdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='first_name',
            field=models.CharField(default='toqa', max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='last_name',
            field=models.CharField(default='alaa', max_length=23),
            preserve_default=False,
        ),
    ]
