# Generated by Django 4.2.8 on 2023-12-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0013_billingdetails_first_name_billingdetails_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='to_be_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
