# Generated by Django 4.2.8 on 2023-12-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0013_alter_product_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
