# Generated by Django 4.2.8 on 2023-12-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0014_billingdetails_to_be_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='zip',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
