# Generated by Django 4.2.8 on 2023-12-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0015_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GroceryApp.category'),
        ),
    ]
