# Generated by Django 4.2.8 on 2023-12-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0016_alter_cartorder_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(default='Fresh Food', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='brand_nationality',
            field=models.CharField(default='Egyptian', max_length=100),
            preserve_default=False,
        ),
    ]
