# Generated by Django 4.2.7 on 2023-12-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0017_product_available_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='price',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
