# Generated by Django 4.2.8 on 2023-12-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0018_remove_cartorder_price_cartorder_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='total_price',
        ),
    ]
