# Generated by Django 4.2.8 on 2023-12-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GroceryApp", "0019_alter_billingdetails_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingdetails",
            name="address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="billingdetails",
            name="apartment",
            field=models.CharField(
                max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="billingdetails",
            name="city",
            field=models.CharField(
                max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="billingdetails",
            name="email",
            field=models.CharField(
                max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="billingdetails",
            name="governorate",
            field=models.CharField(
                max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="billingdetails",
            name="payment_method",
            field=models.CharField(
                max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="billingdetails",
            name="phone",
            field=models.CharField(
                max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                ],
                
                default="Processing",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="product_status",
            field=models.CharField(
                blank=True, max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, null=True
            ),
        ),
    ]
