# Generated by Django 4.2.8 on 2024-01-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GroceryApp", "0021_remove_wishlist_product_remove_wishlist_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.URLField(blank=True, null=True),
        ),
    ]
