# Generated by Django 4.2.8 on 2024-01-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GroceryApp", "0022_alter_product_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimages",
            name="images",
            field=models.URLField(blank=True, null=True),
        ),
    ]
