# Generated by Django 4.2.8 on 2024-01-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GroceryApp", "0024_alter_category_img_alter_product_product_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="exp_date",
            field=models.DateTimeField(null=True),
        ),
    ]
